// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWMsuoso7rAm7UlG4NZuJS9cH53c2-C-w',
    appId: '1:193019775915:web:e51d1d2c23e78d17d520ee',
    messagingSenderId: '193019775915',
    projectId: 're-win-cc0a1',
    authDomain: 're-win-cc0a1.firebaseapp.com',
    storageBucket: 're-win-cc0a1.firebasestorage.app',
    measurementId: 'G-M55MFWZPPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRtdrcqDjRjVQPRszHNX-ouTAxQ9mlZk',
    appId: '1:193019775915:android:7159af34b706179dd520ee',
    messagingSenderId: '193019775915',
    projectId: 're-win-cc0a1',
    storageBucket: 're-win-cc0a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7LjFAXCFiefKYzzObjulb9gBXah4U6g',
    appId: '1:193019775915:ios:8ed93a59e569f42ad520ee',
    messagingSenderId: '193019775915',
    projectId: 're-win-cc0a1',
    storageBucket: 're-win-cc0a1.firebasestorage.app',
    iosBundleId: 'com.example.recyclingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7LjFAXCFiefKYzzObjulb9gBXah4U6g',
    appId: '1:193019775915:ios:8ed93a59e569f42ad520ee',
    messagingSenderId: '193019775915',
    projectId: 're-win-cc0a1',
    storageBucket: 're-win-cc0a1.firebasestorage.app',
    iosBundleId: 'com.example.recyclingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWMsuoso7rAm7UlG4NZuJS9cH53c2-C-w',
    appId: '1:193019775915:web:e361834d558c2227d520ee',
    messagingSenderId: '193019775915',
    projectId: 're-win-cc0a1',
    authDomain: 're-win-cc0a1.firebaseapp.com',
    storageBucket: 're-win-cc0a1.firebasestorage.app',
    measurementId: 'G-EHKWD17RKN',
  );
}
